meta:
  version: 2
  flow: FABulousTile
  substituting_steps:
    # Don't resize the buffers
    OpenROAD.Resizer*: null
    OpenROAD.RepairDesign*: null

FABULOUS_TILE_DIR: dir::. #tiles/W_TT_IF

# Basics
DESIGN_NAME: W_TT_IF
VERILOG_FILES:
  - dir::../../models_pack.v
  - dir::../../custom.v
FABULOUS_EXTERNAL_SIDE: W

# Disable timing driven placement
# as it would resize the buffers
PL_TIME_DRIVEN: false

# Clock
CLOCK_PERIOD: 20
CLOCK_PORT: UserCLK

# Area
FP_SIZING: absolute
pdk::sky130A:
    DIE_AREA: [0, 0, 205, 56.25]
pdk::ihp-sg13g2:
    # Width should be multiple of 0.48 (Metal2 pitch)
    # Height should be multiple of 0.42 (Metal3 pitch)
    DIE_AREA: [0, 0, 107.52, 215.04]
    
    PL_TARGET_DENSITY_PCT: 94
    SYNTH_STRATEGY: "AREA 2" # "AREA 0" "AREA 1" "AREA 2" "AREA 3"
