meta:
  version: 2
  flow: FABulousTile
  substituting_steps:
    # Don't resize the buffers
    OpenROAD.Resizer*: null
    OpenROAD.RepairDesign*: null

FABULOUS_TILE_DIR: dir::. #tiles/LUT4AB

# Basics
DESIGN_NAME: LUT4AB
VERILOG_FILES:
  - dir::../../models_pack.v
  - dir::../../custom.v

# Disable timing driven placement
# as it would resize the buffers
PL_TIME_DRIVEN: false

SYNTH_STRATEGY: "AREA 2" # "AREA 0" "AREA 1" "AREA 2" "AREA 3"

# Clock
CLOCK_PERIOD: 20
CLOCK_PORT: UserCLK

# Area
FP_SIZING: absolute
pdk::sky130A:
    DIE_AREA: [0, 0, 205, 225]
    PL_TARGET_DENSITY_PCT: 58
pdk::ihp-sg13g2:
    # Width should be multiple of 0.48 (Metal2 pitch)
    # Height should be multiple of 0.42 (Metal3 pitch)
    
    #DIE_AREA: [0, 0, 231.84, 241.92]
    #PL_TARGET_DENSITY_PCT: 80
    
    #DIE_AREA: [0, 0, 227.04, 237.72]
    #PL_TARGET_DENSITY_PCT: 82
    
    #DIE_AREA: [0, 0, 207.84, 220.92]
    #PL_TARGET_DENSITY_PCT: 96
    
    DIE_AREA: [0, 0, 215.04, 215.04]
    PL_TARGET_DENSITY_PCT: 96
