meta:
  version: 2
  flow: FABulousFabric
  substituting_steps:
    # Save some time
    Magic.DRC: null
    #KLayout.DRC: null

    # Add steps for LVS with KLayout
    #+Checker.LVS: OpenROAD.WriteCDL
    #+OpenROAD.WriteCDL: KLayout.LVS
    
    # The new version of OpenROAD says
    # during DP it needs stdcell rows
    # (although we don't use stdcells)
    OpenROAD.DetailedPlacement: null

# Basics
DESIGN_NAME: eFPGA
VERILOG_FILES: []

# No extract-unique, because the power straps
# are connected in the top-level integration
MAGIC_NO_EXT_UNIQUE: true

# Unfortunately needed
GRT_ALLOW_CONGESTION: true

# FABulous config
FABULOUS_FABRIC_CONFIG: dir::fabric.csv
FABULOUS_TILE_LIBRARY: dir::../tile_library/tiles/

FABULOUS_TILE_SPACING: 0
# Vertical spacing should be multiple of 0.42 (Metal2 pitch)
# Horizontal spacing should be multiple of 0.48 (Metal3 pitch)
# The halo was chosen so that there's just enough space for the pins
# except for the bottom: here the clock net needs to be routed
FABULOUS_HALO_SPACING: [ 0.48, 4.2, 0.48, 0.48 ]

# Match spacing if possible
FP_IO_HLENGTH: 0.48
FP_IO_VLENGTH: 0.48

FABULOUS_TILE_SIZES:
  LUT4AB:       [ 215.04, 215.04 ]
  NW_term:      [ 107.52, 53.76 ]
  NE_term:      [ 107.52, 53.76 ]
  SW_term:      [ 107.52, 53.76 ]
  SE_term:      [ 107.52, 53.76 ]
  "*_IO4":      [ 215.04, 53.76 ]
  "*_TT_IF":    [ 107.52, 215.04 ]
  "IHP_SRAM_*": [ 107.52, 215.04 ]

# Save on file space by sharing same cells
PRIMARY_GDSII_STREAMOUT_TOOL: klayout
#KLAYOUT_CONFLICT_RESOLUTION: SkipNewCell

# The pin placer tool has a default min distance between pins of 2 routing tracks.
# Allow to place pins everywhere on the routing grid.
FP_IO_MIN_DISTANCE: 0.42 # horizontal grid distance

# Manual pin placement to prevent congestion
FABULOUS_MANUAL_PINS:

    "UserCLK": [Metal2, 5.76, 0.24, 0.4, 0.48]

    "FrameStrobe[0]": [Metal2, 10.56, 0.24, 0.4, 0.48]
    "FrameStrobe[1]": [Metal2, 15.36, 0.24, 0.4, 0.48]
    "FrameStrobe[2]": [Metal2, 20.16, 0.24, 0.4, 0.48]
    "FrameStrobe[3]": [Metal2, 24.96, 0.24, 0.4, 0.48]
    "FrameStrobe[4]": [Metal2, 29.76, 0.24, 0.4, 0.48]
    "FrameStrobe[5]": [Metal2, 34.56, 0.24, 0.4, 0.48]

    "FrameStrobe[109]": [Metal2, 1021.44, 0.24, 0.4, 0.48]
    "FrameStrobe[110]": [Metal2, 1026.24, 0.24, 0.4, 0.48]

    "FrameStrobe[111]": [Metal2, 1031.04, 0.24, 0.4, 0.48]
    "FrameStrobe[112]": [Metal2, 1035.84, 0.24, 0.4, 0.48]
    "FrameStrobe[113]": [Metal2, 1040.64, 0.24, 0.4, 0.48]
    "FrameStrobe[114]": [Metal2, 1045.44, 0.24, 0.4, 0.48]
    "FrameStrobe[115]": [Metal2, 1050.24, 0.24, 0.4, 0.48]
    "FrameStrobe[116]": [Metal2, 1055.04, 0.24, 0.4, 0.48]
    "FrameStrobe[117]": [Metal2, 1059.84, 0.24, 0.4, 0.48]
    "FrameStrobe[118]": [Metal2, 1064.64, 0.24, 0.4, 0.48]
    "FrameStrobe[119]": [Metal2, 1069.44, 0.24, 0.4, 0.48]
    
    "FrameData[22]": [Metal3, 0.24, 1815.66, 0.48, 0.4]
    "FrameData[23]": [Metal3, 0.24, 1817.34, 0.48, 0.4]
    "FrameData[24]": [Metal3, 0.24, 1819.02, 0.48, 0.4]
    "FrameData[25]": [Metal3, 0.24, 1820.70, 0.48, 0.4]
    "FrameData[26]": [Metal3, 0.24, 1822.38, 0.48, 0.4]
    "FrameData[27]": [Metal3, 0.24, 1824.06, 0.48, 0.4]
    "FrameData[28]": [Metal3, 0.24, 1825.74, 0.48, 0.4]
    "FrameData[29]": [Metal3, 0.24, 1827.42, 0.48, 0.4]
    "FrameData[30]": [Metal3, 0.24, 1829.10, 0.48, 0.4]
    "FrameData[31]": [Metal3, 0.24, 1830.78, 0.48, 0.4]
    
# Clock
CLOCK_PERIOD: 20
CLOCK_PORT: UserCLK

# Routing
RT_CLOCK_MAX_LAYER: TopMetal1
RT_MAX_LAYER: TopMetal1
DRT_MAX_LAYER: TopMetal1

# Disable stdcells
#SYNTH_ELABORATE_ONLY: true
RUN_POST_GPL_DESIGN_REPAIR: false
RUN_POST_CTS_RESIZER_TIMING: false
DESIGN_REPAIR_BUFFER_INPUT_PORTS: false
FP_PDN_ENABLE_RAILS: false
RUN_ANTENNA_REPAIR: false
RUN_FILL_INSERTION: false
RUN_TAP_ENDCAP_INSERTION: false
RUN_CTS: false
RUN_IRDROP_REPORT: false
ERROR_ON_SYNTH_CHECKS: false

# PDN (of the tiles) TODO
# Needs to be the same PDN setting as for the tiles
# as it is used to overly vertical power straps
# at the same position as at the tiles
FP_PDN_VERTICAL_LAYER: TopMetal1
FP_PDN_HORIZONTAL_LAYER: TopMetal2

FP_PDN_VWIDTH: 2.2
FP_PDN_VSPACING: 4.0
FP_PDN_VPITCH: 75.6
FP_PDN_VOFFSET: 13.6

FP_PDN_HWIDTH: 2.0
FP_PDN_HSPACING: 4.0
FP_PDN_HPITCH: 75.6
FP_PDN_HOFFSET: 13.57

VDD_PIN: VPWR
GND_PIN: VGND
