meta:
  version: 2
  flow: FABulousFabric
  substituting_steps:
    # Save some time
    Magic.DRC: null
    KLayout.DRC: null

    # Add steps for LVS with KLayout
    #+Checker.LVS: OpenROAD.WriteCDL
    #+OpenROAD.WriteCDL: KLayout.LVS
    
    # New version of OpenROAD says
    # that it needs stdcell rows
    OpenROAD.DetailedPlacement: null

# Basics
DESIGN_NAME: eFPGA
VERILOG_FILES: []

# No extract-unique, because the power straps
# are connected in the top-level integration
MAGIC_NO_EXT_UNIQUE: true

# Unfortunately needed
GRT_ALLOW_CONGESTION: true

# FABulous config
FABULOUS_FABRIC_CONFIG: dir::fabric.csv
FABULOUS_TILE_LIBRARY: dir::../tile_library/tiles/

FABULOUS_TILE_SPACING: 0
# Vertical spacing should be multiple of 0.42 (Metal2 pitch)
# Horizontal spacing should be multiple of 0.48 (Metal3 pitch)
# The halo was chosen so that there's just enough space for the pins
# except for the bottom: here the clock net needs to be routed
FABULOUS_HALO_SPACING: [ 0.48, 4.2, 0.48, 0.48 ]

# Match spacing if possible
FP_IO_HLENGTH: 0.48
FP_IO_VLENGTH: 0.48

FABULOUS_TILE_SIZES:
  LUT4AB:       [ 215.04, 215.04 ]
  NW_term:      [ 107.52, 53.76 ]
  NE_term:      [ 107.52, 53.76 ]
  SW_term:      [ 107.52, 53.76 ]
  SE_term:      [ 107.52, 53.76 ]
  "*_IO":       [ 215.04, 53.76 ]
  "*_TT_IF":    [ 107.52, 215.04 ]
  "IHP_SRAM_*": [ 107.52, 215.04 ]

# Save on file space by sharing same cells
PRIMARY_GDSII_STREAMOUT_TOOL: klayout
#KLAYOUT_CONFLICT_RESOLUTION: SkipNewCell

# The pin placer tool has a default min distance between pins of 2 routing tracks.
# Allow to place pins everywhere on the routing grid.
FP_IO_MIN_DISTANCE: 0.42 # horizontal grid distance

# Manual pin placement to prevent congestion
#FABULOUS_MANUAL_PINS:
#    "FrameData[0]": [Metal2, 0.24, 3453.92, 0.48, 0.4]

# Clock
CLOCK_PERIOD: 20
CLOCK_PORT: UserCLK

# Routing
RT_CLOCK_MAX_LAYER: TopMetal1
RT_MAX_LAYER: TopMetal1
DRT_MAX_LAYER: TopMetal1

# Disable stdcells
#SYNTH_ELABORATE_ONLY: true
RUN_POST_GPL_DESIGN_REPAIR: false
RUN_POST_CTS_RESIZER_TIMING: false
DESIGN_REPAIR_BUFFER_INPUT_PORTS: false
FP_PDN_ENABLE_RAILS: false
RUN_ANTENNA_REPAIR: false
RUN_FILL_INSERTION: false
RUN_TAP_ENDCAP_INSERTION: false
RUN_CTS: false
RUN_IRDROP_REPORT: false
ERROR_ON_SYNTH_CHECKS: false

# PDN (of the tiles) TODO
# Needs to be the same PDN setting as for the tiles
# as it is used to overly vertical power straps
# at the same position as at the tiles
FP_PDN_VERTICAL_LAYER: TopMetal1
FP_PDN_HORIZONTAL_LAYER: TopMetal2

FP_PDN_VWIDTH: 2.2
FP_PDN_VSPACING: 4.0
FP_PDN_VPITCH: 75.6
FP_PDN_VOFFSET: 13.6

FP_PDN_HWIDTH: 2.0
FP_PDN_HSPACING: 4.0
FP_PDN_HPITCH: 75.6
FP_PDN_HOFFSET: 13.57

VDD_PIN: VPWR
GND_PIN: VGND
