meta:
  version: 2
  flow: FABulousTile
  substituting_steps:
    # Don't resize the buffers
    OpenROAD.Resizer*: null
    OpenROAD.RepairDesign*: null

FABULOUS_TILE_DIR: dir::. #tiles/E_TT_IF2

# Basics
DESIGN_NAME: E_TT_IF2
FABULOUS_SUPERTILE: true
VERILOG_FILES:
  - dir::../../models_pack.v
  - dir::../../custom.v
FABULOUS_EXTERNAL_SIDE: E

# Disable timing driven placement
# as it would resize the buffers
PL_TIME_DRIVEN: false

# Seems to add a few buffers too
PL_ROUTABILITY_DRIVEN: false

# Clock
CLOCK_PERIOD: 20
CLOCK_PORT: Tile_X0Y1_UserCLK

# Area
FP_SIZING: absolute
pdk::ihp-sg13g2:
    # Width should be multiple of 0.48 (Metal2 pitch)
    # Height should be multiple of 0.42 (Metal3 pitch)
    DIE_AREA: [0, 0, 107.52, 430.08]
    
    PL_TARGET_DENSITY_PCT: 84
    SYNTH_STRATEGY: "AREA 0" # "AREA 0" "AREA 1" "AREA 2" "AREA 3"
